### ISSUE TITLE
Ничего не делает

### ISSUE THREAD

**Issue by ghtg** [granlovestea/SkysmartAnswers#1]
Открываю main.exe ввожу туда номер комнаты и прога закрывается. Никаких файлов не создается с ответами. Возможно надо вписать auth token в соответствующий файл, но я не знаю, где его(токен) брать. Помогите пожалуйста.

**Comment by Thjko** [comment]
Столкнулся с такой же проблемой, ты нашел решение?

**Comment by ghtg** [comment]
> Столкнулся с такой же проблемой, ты нашел решение?

Нет, жду, пока разработчик не обновит или ответит.

**Comment by granlovestea** [comment]
Исправил некоторые ошибки которые могли к этому привести, также расширил гайд, будут еще вопросы - пишите.
