### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by mishailovic** [granlovestea/SkysmartAnswers#3]
Скайсмарт теперь палит открытие дебаг консоли и рефрешит токен, будут ли идеи по данному вопросу?

**Comment by granlovestea** [comment]
Сейчас попробовал все сделать на Google Chrome - все получилось и работает как раньше. Также, поперезагружал страницу, попереоткрывал dev tools, однако auth token все тот же. Консоль действительно палится и очищается, но токен остается все тот же. Пришли полный алгоритм своих действий при использовании программы, возможно делаешь что-то не так (копируешь токен/хэш комнаты с лишним пробелом или что-то такое)

**Comment by mishailovic** [comment]
проблема решилась сама собой) наверное комната была с багом, там были неправильные ответы
